/*****************************************************
 *
 * Language text: Swedish
 *
 * @author Glenn De Backer <glenn@simplicity.be>
 *
 *****************************************************/
#include "../../include/se.h"

std::string seText = R"(En fremling, som uppehåller sig någon tid i London, underlåter väl icke gerna, ifall han har sinne för folksång och folkmelodier, att besöka Evans' Music and Supper Rooms i Covent-garden. Bland de många sånger, hvilka hafva bifallet för dagen och för närvarande äro gängse hos folket, träffas hans öron der af en dikt med egendomligt innehåll. Den berömde sir H.R. Bishop har arrangerat musiken, och genom det hela går en ton af skogsdoft och jägarlust. "Robin Hood, så säges det i sången, är den bäste jägare, som någonsin spände sin båge i en grönskande skog. Till ljudet af hans gälla horn svarar ekot vidt och bredt, och lyssnande samla sig de gula rådjuren mellan träden. Och har väl någon sett en tärna så öm som Marion, den grönklädde skogsmannens stolthet? Hell, denna jungfru-drottning, den milda blomman! Vi lefva och dö henne trogne. Hell Robin och Marion, Robin och Marion! länge skall Sherwood genljuda af deras ära." Så ungefär lyder sången, hvilken ännu bevarar minnet af den engång så berömde fribytaren och hans tärna, under hvilken sednares namn den tar tillfället i akt, att bringa ett hell åt Englands jungfru-drottning, "Maiden-queen". Detta kan icke vara någon annan än drottning Elisabeth.

Ifrån hennes tid har således denna sång lefvat i tvenne århundraden och höres ännu i dag uti Evans' Music and Supper Rooms i London.

Lider det emot aftonen, så att byfolket efter sin vana samlas utanför värdshuset, slår det icke felt att någon kringvandrande fiddler infinner sig med instrumentet under armen, och ur sitt visförråd bland annat framtar äfven några stumpar om Robin Hood och hans fribytare. Lefde blott den åldrige Skipton-minstreln - förutsatt att man befinner sig i West-Riding af Yorkshire - skulle han utan tvifvel kunna förtälja mera än någon lefvande om dessa underbara personligheter.

Men den låghalte Francis King, som kunde berömma sig af att "few Kings had had more ups and downs in the world", är död sedan sexton år, och det kan derföre vara säkrast att man vänder sig till någon åldrig mormoder eller farfader, som för sina barnabarn plägar sjunga gamla visor och ballader. 1 Staffordshire och Herefordshire är ingen brist på sådana. Men framförallt är man i tillfälle att lära känna de odödliga hjeltarne i den engelska folksången, om man deltager i folkförlustelserna, hvarmed vårens ankomst firas öfverallt i bygderne, då ungdomen samlar sig kring majstången och i lustiga may-games ger luft åt sin glada stämning. I Cornwall anställes på den så kallade Furry-day (Floras dag) i början af maj en fest, deri bygdens samtliga befolkning, kransad med blommor och dansande i långa rader, drar omkring ur hus i hus, under sång och musik. "Robin Hood och Little John, sjunga de, hafva vandrat till den glada gröna skogen; låtom ock oss draga dit, att se hvad de begge der beställa, och att jaga i deras sällskap råbockar och hindar, med ett ha-lan-tow, rumble-o." I andra trakter åter, såsom Oxfordshire, Norfolk och Lancasshire, lefver en plägsed, hvilken lifligt påminner om ett åldrigt bruk i vårt eget land. Vid de stora högtiderna, jul, påsk och pingst, bilda sig vandrande sällskaper, hvilka uppföra otympliga föreställningar af ett margfaldigt innehåll, och med möjligast ringa användning af dekorationer ooh kostymer. De kallas Morris- (moorish) dancers, och stående karakterer i deras prestationer, liksom i de ofvannämnde maygames, äro Robin Hood, frier Tuck och maid Marion.

Men dessa ännu lefvande hågkomster äro endast spridda qvarlefvor af en kult, som i sextonde och sjuttonde seklerna var utbredd öfver hela England och Skottland, och hvari Robin Hood i sjelfva verket firades som det glada landtlifvets skyddspatron och genius.

Hans namn och bedrifter lefde i tallösa visor och ordspråk, på flere orter bevarade man hans båge och pilar såsom dyrbara reliker, och fester höllos on the Robin Hodes daie, hvilken var en viss dag i början af våren. Det var den muntra vårkänslan, som gaf sig luft i den dyrkan man sålunda egnade honom, och hvarvid man kan säga, att minstrelen tyckes hafva varit prest och det godmodiga skämtet predikan. Företrädesvis öfvades vid dessa fester målskjutning med båge, i hvilken nationalkonst Robin Hood var det oupphinneliga idealet, äfvensom staffäktning, jemte det man på enkla ställningar af bräder uppförde muntra majspel, i hvilka Robin Hood var majkonung och Marian drottning. Såsom vi sett hafva dessa fester ännu icke utdött, men de firades icke då, såsom nuförtiden, af enskildte; de voro en vigtig samfundsangelägenhet, så att på församlingarnas bekostnad anskaffades Robin Hoods hatt, handskar och banér, silfverpapper och klockor åt dansarene, samt band och målade tyger åt fruntimmerna, liksom ock ur församlingens kassa bestreds the mensterells arfvode samt ersättning för Robin Hoods, maid Marians och öfriga hufvudpersoners möda under året; ty de tyckas varit valda, i likhet med andra församlingens funktionärer, på längre tid; såsom gamla kyrkoräkenskaper från början af sextonde seklet allt noggrant detaljerar.

Må man icke för ringa skatta vigten af dessa landtliga fester. De sutto fast med djupa rötter i folkets inre lif och äro talande vittnen om detsamma. Biskop Latimer i en af sina predikningar inför Edward VI omtalar, huru han en gång på vägen hemåt från London anlände till en liten stad och sände bud, att han följande morgon ernade predika derstädes, "alldenstund, säger han, det var helgedag och detta tycktes mig vara helgedagsverk. Kyrkan låg i min väg, och jag tog min häst samt mitt sällskap och förde dem dit - menande jag skulle finna talrik samling i kyrkan; - men när jag dit anländt, fann jag kyrkodörren fast tillsluten. Jag töfvade der väl mer än en half timme, tills på sistone nyckeln blef funnen och en af församlingen kommer till mig, sägande: 'Herre, detta är en bullersam dag hos oss, vi kunna icke höra eder; det är Robin Hoods dag och församlingen är gången ut att samla löf till festen, så att J vänten den förgäfves'." Och sålunda måste biskopen, som var klädd i sin fulla ornat, öfvergifva predikstolen och lemna plats åt Robin Hood, frier Tuck och maid Marian, hvilka från sin löftheater talte ett gladare språk till menigheten. "Och detta är ingen sak att le åt", fortfar den förbittrade prelaten, "det är en sak att gråta åt, en högst betänklig sak, att föredraga Robin Hood, som var en förrädare och en tjuf, framför Guds ords åhörande och för hans skuld bortstöta en ordets tjenare och missakta hans embete." Detta var en mägtig stämmas protest emot folkhjeltens anseende, och redan nu begynte mången lärd och alvarlig man säga liksom ordspråksvis om något tomt och fåfängligt, att "det kan vara godt nog åt dårar, liksom historierna om Robin Hood.")";
