/*****************************************************
 *
 * Language text: Italian
 *
 * @author Glenn De Backer <glenn@simplicity.be>
 *
 *****************************************************/

#include "../include/es.h"

std::string itText = R"(I mercanti genovesi e veneziani non potevano rimanere indifferenti alle esplorazioni che arditi viaggiatori tentavano nell'Asia centrale, l'India e la China. Essi comprendevano che queste contrade offrirebbero in breve un nuovo sfogo ai loro prodotti, e che, d'altra parte, utili immensi si ricaverebbero dall'importazione in Occidente di mercanzie di fabbricazione orientale. Gl'interessi del commercio dovevano quindi lanciare dei nuovi cercatori sulle vie delle scoperte. Queste furono le ragioni che decisero due nobili veneziani ad abbandonare la loro patria ed a sfidare tutte le fatiche e tutti i pericoli di quei perigliosi viaggi, allo scopo d'estendere le loro relazioni commerciali.

Questi due Veneziani appartenevano alla famiglia Polo, la quale traeva origine da Sebenico, in Dalmazia, ed erasi stabilita sino dal 1033 in Venezia. È nel secolo XIII che noi troviamo questa famiglia divisa in due rami; uno dei quali abitava nella contrada di San Felice, l'altro in quella di San Geremia.

I Polo di San Felice, datisi già da più anni al commercio, avevano in esso trovata larghissima fonte di ricchezze, che aveanli posti a livello delle famiglie patrizie di Venezia.

Nel 1260, i fratelli Niccolò e Matteo o Maffio, figliuoli di Andrea, che già prima del 1250 avevano stabilito un banco a Costantinopoli, terra più veneziana che greca dopo l'impresa del Dandolo, si recarono con una paccotiglia considerevole di gioielli nel Sudac, in Crimea, ove la loro casa possedeva un altro banco diretto da un loro fratello maggiore, Andrea Polo. Da quel punto, risalendo verso il nord-est, e traversando il paese di Comania, giunsero sul Volga, ove teneva il suo campo Berke-Kan signore dei Tartari occidentali. Questo principe mongollo accolse benissimo i due negozianti di Venezia, e comperò i gioielli che gli offersero pel doppio del valore, facendo inoltre ad essi ricchissimi doni.

Niccolò e Matteo rimasero un anno nel campo mongollo; finchè, nel 1262, scoppiò una guerra tra Berke ed il principe Ulagù o Alau, signore dei Tartari di Levante, e conquistatore della Persia. I due fratelli, non volendo avventurarsi in mezzo a contrade battute dai Tartari, preferirono recarsi a Boukhara, che era la principale residenza di Berke, e colà rimasero tre anni e mezzo. Ma quando Berke fu vinto, e presa la sua capitale, un'ambasciata d'Ulagù invitò i due Veneziani a seguirli verso la residenza del Gran Kan dei Tartari, che avrebbe fatto loro ottima accoglienza. Kublai-Kan, quarto figlio di Gengis-Kan, era imperatore della China, e teneva allora la residenza d'estate in Mongolia, a Cai-ping-fu, sulla frontiera dell'impero Chinese.

I due mercanti veneziani partirono, e spesero un anno intero nel traversare quell'immensa estensione di paese che divide Boukhara dai confini settentrionali della China. Kublai-Kan fu lietissimo di ricevere quegli stranieri, venuti da paesi occidentali. Fece loro molte feste, e li interrogò con premura sugli avvenimenti che accadevano in Europa, chiedendo molti particolari intorno agli imperatori e re, alla loro amministrazione, ai loro metodi di guerra; poscia li intrattenne lungo tempo del pontefice e degli affari della Chiesa latina.

Matteo e Niccolò, già pratici degli usi tartareschi e della lingua, risposero francamente a tutte le domande dell'imperatore, al quale tanto piacquero i due Veneziani, che pensò d'inviarli come suoi ambasciatori a Sua Santità. I mercanti accettarono con riconoscenza, giacchè in tale alta condizione il loro ritorno doveva effettuarsi in condizioni vantaggiosissime.

Kublai-Kan fece stendere lettere in lingua turca, nelle quali chiedeva a Sua Santità Clemente IV, d'inviargli cento missionari per convertire gl'idolatri al cristianesimo; poscia licenziò i due Veneziani, dando ad essi per compagno di viaggio uno de' suoi baroni, chiamato Cogatal, ed incaricandoli di riportargli un vasetto dell'olio della lampada sacra che arde continuamente sulla tomba di Gesù Cristo a Gerusalemme.

I due fratelli, muniti di passaporto su tavoletta d'oro, che metteva a loro disposizione uomini e cavalli in tutta l'estensione dell'impero, presero congedo dal Gran Kan e si misero in viaggio nel 1266. In breve però il barone Cogatal cadde ammalato. I Veneziani, costretti a separarsi da lui, proseguirono il loro cammino, e, malgrado gli aiuti che ricevettero, impiegarono non meno di tre anni per giungere a Giazza, porto dell'Armenia Minore. Da Giazza si portarono ad Acri, ove arrivarono verso la fine dell'anno 1269. Colà seppero della morte di papa Clemente IV, verso il quale erano diretti. Ma il legato apostolico Tebaldo risiedeva in quella città; egli accolse i due Veneziani, e sentendo quale fosse la missione di cui il Gran Kan li aveva incaricati, li esortò ad attendere l'elezione del nuovo papa.

Matteo e Niccolò, assenti dalla loro patria da ben diciannove anni, pensarono, intanto che il nuovo pontefice fosse eletto, di rivedere Venezia e la famiglia. Si recarono a Negroponte, ove s'imbarcarono sopra una nave, che li condusse direttamente alla loro città natale.

Sbarcando, Niccolò apprese la morte di sua moglie e la nascita di un figlio, nato pochi mesi dopo la sua partenza, nel 1251. Quel figlio si chiamava Marco. Egli è ben da credere che al dolore del marito dovesse recare grande conforto la gioia del padre che trovava questo figliuolo, quasi a tenergli luogo della donna perduta. Durante due anni i fratelli Polo, cui stava a cuore di adempiere la loro missione, aspettarono a Venezia l'elezione del nuovo papa. Ma poichè questa tardava, parve loro di non poter più oltre differire il loro ritorno presso l'imperatore dei Mongolli; partirono quindi per Acri, nell'aprile 1271, conducendo seco il giovane Marco, che contava allora ben 19 anni. Ad Acri ritrovarono il legato Tebaldo, che li autorizzò a recarsi a Gerusalemme a prendere l'olio della lampada del Santo Sepolcro. Compiuta quella missione, i Veneziani fecero ritorno ad Acri, e mancando ancora il pontefice, chiesero al legato lettere per Kublai-Kan, nelle quali sembra fosse accennata la morte di Clemente IV. Tebaldo consegnò le lettere, ed i due fratelli tornarono a Giazza. Ivi, con grandissima gioja, seppero che il legato Tebaldo era stato consacrato papa, sotto il nome di Gregorio X, il 1 settembre 1271. Il nuovo pontefice li richiamò immediatamente, ed il re d'Armenia pose una galera a loro disposizione, perchè potessero recarsi più rapidamente ad Acri. Il papa li accolse con premura, consegnò loro lettere per l'imperatore della China, diè loro la compagnia di due frati predicatori, Niccolò da Vicenza e Guglielmo da Tripoli, e la sua benedizione.

Gli ambasciatori, accommiatatisi da Sua Santità, fecero ritorno ad Acri; ma appena giunti in quella città, poco mancò non cadessero prigionieri nelle mani di Boibar Bundoctari, Sultano mamelucco del Cairo, che infestava allora l'Armenia. Spaventati i due frati predicatori di quel brutto principio, rinunciarono a recarsi nella China, e lasciarono ai Veneziani la cura di consegnare all'imperatore mongollo le lettere del pontefice.

È qui che incominciano i grandi viaggi descritti da Marco Polo, dei quali noi parleremo in progresso. Ha egli realmente visitato tutti i paesi e tutte le città ch'egli descrive? No, senza dubbio; e nella sua narrazione, scritta in francese sotto suo dettato da Rusticano da Pisa, è formalmente dichiarato che «Marco Polo, savio e nobile cittadino di Venezia, vide tutto co' propri occhi, e quello che non vide lo seppe dalla bocca di uomini degni di fede.» Ma aggiungiamo che la maggior parte delle città e paesi descritti da Marco Polo vennero realmente da lui percorse. Seguiremo quindi l'itinerario com'è tracciato nel suo racconto, indicando soltanto ciò che il celebre viaggiatore seppe da altri durante le importanti missioni di cui lo incaricò l'imperatore Kublai-Kan. In questo secondo viaggio i Veneziani non seguirono esattamente la medesima strada che Matteo e Niccolò avevano presa recandosi la prima volta verso l'imperatore della China. Essi erano passati a settentrione dei monti Celesti, che sono i monti Thiânscian-pe-lu; il che aveva allungato il loro cammino. Questa volta piegarono a mezzodì pei monti stessi; eppure, benchè quella strada fosse più corta dell'altra, impiegarono non meno di tre anni a percorrerla, a cagione delle pioggie e degli straripamenti dei grandi fiumi. Sarà facile seguire questo itinerario sopra una carta dell'Asia, dacchè ai nomi antichi della storia di Marco Polo, non facili ad intendersi nel suo libro, nel quale non è seguíto l'ordine del viaggio, ed è fatta confusione delle cose udite e delle vedute, abbiamo sostituito dappertutto i nomi esatti della cartografia moderna.)";
