/*****************************************************
 *
 * Language text: Lorem Ipsum
 *
 * @author Glenn De Backer <glenn@simplicity.be>
 *
 *****************************************************/

#include "../include/lorem.h"

std::string loremText = R"(Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam condimentum metus est, quis convallis est convallis pharetra. Cras semper, tellus in volutpat placerat, ligula erat accumsan felis, at efficitur ex magna eget nisi. In aliquam pretium suscipit. Donec tincidunt tortor aliquam magna aliquet, vestibulum iaculis risus pharetra. Sed quis diam ligula. Ut ut turpis sed tellus vehicula pharetra lobortis porttitor eros. Proin pellentesque quis arcu vel congue. Integer vulputate tempor egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla ultrices quam at velit elementum consectetur.

Aenean ipsum purus, blandit et porta quis, luctus id turpis. Cras semper, mauris at fermentum iaculis, urna felis ultrices ligula, non consectetur augue eros a turpis. Morbi bibendum velit purus, nec congue nulla sagittis at. Morbi aliquet vehicula aliquet. Nulla sit amet viverra risus. Maecenas non varius justo. Mauris pulvinar est et lobortis vehicula. Quisque id venenatis nisl. Praesent tempor at lacus ut pellentesque. Phasellus lobortis cursus metus ut gravida. Proin at eros varius, gravida elit et, rhoncus purus. Vivamus nec ante felis. Duis posuere dui eget congue facilisis. Nam mollis pharetra sapien, in lacinia elit vehicula tincidunt. Suspendisse accumsan bibendum maximus. Maecenas pretium justo magna, sed egestas mi vulputate et.

Cras at auctor quam, quis facilisis ante. Donec pulvinar quam id congue condimentum. Phasellus in tortor nisl. Ut nec lacinia odio, eu ultricies nulla. Integer in accumsan quam. In hac habitasse platea dictumst. Suspendisse justo odio, rutrum sed ligula sit amet, placerat viverra nibh. Curabitur non elit ac libero bibendum convallis ac quis turpis. Morbi ullamcorper magna id arcu fermentum volutpat. Mauris tristique rutrum enim vitae venenatis. Maecenas dictum, nisl in mollis gravida, velit magna volutpat lacus, eu dapibus dui lorem nec nibh. Cras at nisi neque. Nunc in congue nunc. Duis quis sodales ipsum, id consequat ex.

In sit amet elementum tortor. Aenean pharetra lobortis sagittis. Donec dignissim ut erat at volutpat. Quisque porta eros id faucibus mollis. Cras a tristique arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla mattis consectetur tristique. Sed ullamcorper orci quam, ut viverra felis posuere non. Ut et eros est. Donec est ipsum, ullamcorper id pulvinar ut, fringilla mollis massa. Pellentesque at sapien ac augue facilisis posuere. Mauris suscipit ultrices felis, vitae gravida arcu tempor eu. Sed quis nunc vel eros volutpat aliquam. Maecenas ut turpis sit amet eros tempor porttitor et eu risus. Integer enim sem, vehicula et turpis ut, sodales consequat orci.

Nam in tellus finibus eros scelerisque porta egestas non erat. Pellentesque elementum vehicula risus sed rhoncus. Vivamus dapibus ut elit sed varius. Suspendisse id lorem eget nulla mollis feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse ut elementum mauris. Sed et iaculis elit. In at tellus lacinia nisl tempor viverra. Vivamus sagittis velit vel tincidunt bibendum. Curabitur augue orci, consectetur et purus eget, hendrerit tristique arcu. Cras luctus, quam placerat sagittis ullamcorper, enim lacus dictum tortor, eu tristique neque magna a odio. Nam interdum tincidunt orci, a aliquam velit mollis vitae. Vivamus euismod, nisl a dictum vehicula, odio lacus vehicula mauris, ut luctus sem nisl lobortis nibh. Etiam a scelerisque velit. Vestibulum maximus, sapien a bibendum aliquet, lorem lorem blandit risus, sed tincidunt erat felis nec nunc.

Fusce dolor diam, congue sed bibendum ac, sodales nec felis. Sed lacus nisl, ultricies eu metus vitae, malesuada interdum elit. Donec sed justo vehicula, feugiat nibh in, varius velit. Aliquam nec lobortis leo. Etiam volutpat tempus leo, id suscipit lacus consequat sed. Nunc id malesuada diam. Nam semper accumsan vehicula. Donec hendrerit eros sodales erat finibus ultrices. Sed iaculis ut nulla id finibus. Ut commodo vitae felis nec ullamcorper. Donec egestas enim eu sapien finibus pretium. Phasellus suscipit nulla in congue bibendum. Suspendisse at dictum lectus, ut venenatis libero. Donec efficitur tortor ipsum, vitae scelerisque magna rutrum a.

Morbi vel tempus nulla. Sed in tellus est. Etiam tincidunt ac metus vel viverra. Mauris vehicula arcu eu sapien sodales, id gravida diam placerat. Integer eu lacinia lacus, eget sodales justo. Pellentesque bibendum cursus elementum. Suspendisse leo ipsum, pharetra ut nisi et, faucibus sagittis dolor.

In sed eleifend sem. Cras id justo sed ex pellentesque auctor. Phasellus vel varius lacus, tempus vehicula sem. Nulla ac purus dolor. Nulla sollicitudin odio in dolor egestas, eget mattis tortor mattis. Curabitur tristique nisi quis sem eleifend ullamcorper. Nulla non sagittis ligula, ut consectetur erat. Nullam congue neque eu porta luctus. Etiam condimentum sem euismod orci ornare consectetur. Praesent semper fringilla eros sit amet vulputate. Duis dapibus, eros eget pulvinar rhoncus, ligula neque tempor nisi, ac blandit turpis tellus mattis enim. Donec elementum fermentum turpis non mollis. Suspendisse nec ultrices nibh, suscipit cursus risus. Etiam magna augue, auctor in mauris ac, ultricies facilisis justo. Mauris eleifend sollicitudin dolor, ac auctor purus rutrum et.

Aliquam sit amet euismod odio. Phasellus sit amet consequat mauris. Cras eu pellentesque leo. Etiam sit amet ex in nibh interdum convallis. Nullam sit amet sagittis tellus, vel vestibulum urna. Donec ultricies gravida pellentesque. Nulla tellus turpis, porta id lacinia vitae, ultricies at lacus. Aenean dapibus nibh lacus, vitae placerat lacus blandit et. Donec id sapien sed leo sollicitudin faucibus sit amet eget turpis. Curabitur eget sem in odio iaculis maximus. Nullam vel maximus felis, vitae dignissim felis. Maecenas tempor leo ut libero molestie molestie. Proin id pharetra mi.

Maecenas imperdiet vel nisl vel molestie. Donec vulputate neque eu sem viverra, suscipit porta leo accumsan. Proin elit augue, tempor ac congue et, lobortis in orci. Aliquam eu viverra massa. Etiam tincidunt eu nisi vitae porta. Nunc non magna ac nibh luctus volutpat at sed magna. Mauris luctus lacus massa, a tempor nibh aliquam eget. Morbi arcu neque, maximus id massa quis, sodales aliquet lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Aenean in molestie odio. Morbi ultricies libero sit amet pellentesque viverra. Phasellus est enim, pretium non consequat sed, imperdiet eget nulla. Morbi molestie nulla nec est efficitur, nec aliquet lectus mollis. Suspendisse posuere fermentum erat, id bibendum ligula laoreet nec. Pellentesque mollis metus arcu, et posuere lectus vehicula volutpat. Quisque vitae aliquam lorem. Fusce tellus leo, blandit id orci nec, pellentesque convallis augue. Proin at quam at metus consequat sagittis non vel diam. Aenean gravida eros non erat maximus, ut scelerisque justo pretium. Duis nec dolor pellentesque, pharetra dolor sit amet, venenatis lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus ultrices eu leo ut posuere.

Nunc dolor justo, feugiat vitae nisi eget, convallis maximus dolor. Nam ut dolor at ante elementum rutrum. Suspendisse maximus leo eu nisl rhoncus, in dignissim nisl rhoncus. Vivamus in sapien vehicula, finibus sem sit amet, venenatis orci. Vestibulum volutpat mollis nibh, eu imperdiet nibh semper at. In faucibus dolor vel erat consequat varius. Morbi porttitor nec est eu hendrerit. Pellentesque suscipit varius dolor vitae luctus. Nulla tempus porta nunc nec lobortis. Fusce convallis molestie libero quis pretium. Duis ac turpis diam. Maecenas hendrerit ut quam eget commodo. Curabitur dapibus tortor non vulputate consequat.

In nec odio tempor, varius tortor eleifend, luctus erat. Pellentesque rhoncus laoreet sem, quis congue risus pulvinar id. Donec bibendum metus erat, eu vehicula tellus tempor et. Praesent vel quam non mauris congue sagittis. Mauris vestibulum lobortis scelerisque. Fusce pellentesque malesuada diam, non mollis erat sagittis ac. Nam luctus tristique sodales. Donec molestie ex pulvinar aliquet dapibus. Pellentesque ipsum lacus, fringilla at pretium ut, consectetur sit amet purus.

Donec felis dui, placerat a sem vel, consectetur laoreet est. Morbi in diam quis justo suscipit eleifend. Mauris velit sem, pretium et imperdiet sit amet, posuere eget purus. In tempus velit vitae erat pretium, eu condimentum sapien elementum. Etiam suscipit, ipsum at ullamcorper pretium, nisi orci ultricies ipsum, vel luctus orci mi et mauris. Suspendisse potenti. Proin porta augue a sapien posuere placerat. Ut vestibulum magna ac libero elementum faucibus. Mauris quis commodo odio, vitae lobortis nisl. In pharetra sem sed nulla dapibus, sed luctus ex luctus. Praesent at turpis at est sollicitudin semper. Pellentesque auctor libero at euismod semper. Fusce vel sem vel orci auctor ullamcorper. Integer dignissim pharetra imperdiet. Sed tempus ligula eget odio semper fermentum.

Proin facilisis, purus quis tempor sodales, mi lectus cursus ipsum, eu accumsan purus neque quis nunc. Pellentesque laoreet quam eu ante rutrum, eu laoreet arcu elementum. Cras libero elit, iaculis at ultricies in, condimentum sed justo. Duis vitae velit iaculis, vehicula odio facilisis, venenatis erat. Curabitur faucibus dolor eros, at consectetur lectus vulputate id. Duis vel eros ipsum. Mauris a magna a purus tempor venenatis. Aenean eleifend leo vitae arcu blandit suscipit. Quisque pharetra elementum sapien vitae hendrerit. Donec at purus non eros viverra finibus.

Sed vitae ante turpis. Nullam eget sem nibh. Nunc urna eros, malesuada ac arcu quis, dictum porttitor tellus. Phasellus id lobortis est. Cras eu turpis ac libero sollicitudin interdum a in lectus. Proin non nulla vel erat facilisis cursus eu ac neque. Donec dui justo, aliquam sit amet mauris ut, imperdiet malesuada diam. Donec nec tempor nibh. Vivamus ut fermentum diam. Ut tincidunt nibh vitae auctor maximus. Pellentesque justo quam, tempus tempor suscipit sed, dignissim at tortor. Aliquam facilisis porta fringilla. Maecenas dictum volutpat odio eu interdum. Donec lectus orci, gravida ac nisl sed, hendrerit euismod libero. Quisque in vestibulum tortor.

Morbi ultrices justo libero. Integer bibendum ligula non aliquam ultrices. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc vitae bibendum est. Nunc placerat massa lectus, quis ultricies eros porta non. Nullam vel auctor leo. Donec pulvinar massa a sapien facilisis volutpat et nec tellus. Proin nisl mauris, molestie vitae sodales in, tincidunt id odio. Quisque a molestie dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec congue gravida mauris, a fringilla lorem. Proin eu dui ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce eget nulla nisi. Phasellus in neque et libero elementum gravida.

Mauris vulputate eu sapien nec viverra. In ac metus erat. Nulla lorem turpis, pulvinar at pulvinar vel, auctor vel urna. Sed porttitor ornare justo, vel faucibus ipsum eleifend at. Aliquam mollis fermentum congue. Duis et molestie lacus. Cras pretium viverra maximus. Curabitur quis tincidunt arcu. Etiam luctus pretium massa, et lacinia sapien varius ac.

Morbi sed accumsan lorem, ut mattis nisl. In dolor urna, rhoncus id sem vel, lacinia efficitur nibh. In vulputate, nulla ut commodo molestie, nisi justo pulvinar justo, quis dignissim urna mi et ligula. Vivamus nec tristique velit. Aenean pulvinar eget felis eget imperdiet. Mauris ut mi vitae arcu semper maximus. Fusce pulvinar lacinia augue in malesuada. Praesent malesuada mattis mollis. Donec semper magna ligula, vel aliquam ante bibendum non. Vestibulum quis lacus at nisl semper porta. Duis quis orci diam. Sed nec arcu a elit gravida rhoncus. Donec et accumsan odio. Nam ornare ultrices semper. Mauris sagittis lorem a elementum hendrerit. Aliquam et tempus nisl, ac rhoncus enim.

Aenean vel aliquam velit. Proin non nisi ac quam vestibulum placerat vel in tellus. Vivamus finibus justo nunc, hendrerit viverra odio auctor nec. Donec varius odio vel purus tempus, sit amet rutrum dolor pharetra. Praesent volutpat sed ipsum laoreet aliquam. Curabitur vulputate nec lacus ullamcorper laoreet. Maecenas vitae elit mauris.)";
